# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
image: zelenjak.arnes.si:5000/arnes/php-app-builder:8.0

variables:
    PLUGIN_PATH: "course/format/weeksrev"
    PLUGIN_NAME: "format_weeksrev"
    NEXT_BRANCH: "MOODLE_405_STABLE"

include:
    - project: 'ucilnice/ucilnice'
      ref: 'master'
      file:
        - '/ci/common.yml'
        - '/ci/review.yml'
    - template: 'Code-Quality.gitlab-ci.yml'
    - template: 'Jobs/SAST.gitlab-ci.yml'

cache:
    paths:
    - $HOME/.composer/cache

stages:
    - test
    - push_downstream

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

code_quality:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  services:
  variables:
    DOCKER_SOCKET_PATH: /run/user/993/podman/podman.sock
  tags:
    - code-quality-sans

semgrep-sast:
  rules:
    - when: always

unit_testing:
    stage: test
    extends: .unit_test_template

start_plugin_review:
    extends: .start_plugin_review_template

stop_plugin_review:
    extends: .stop_plugin_review_template

trigger_downstream:
    extends: .trigger_downstream_template
